### ISSUE TITLE
Umbrella Issue: kubeadm operator v0.1.0

### ISSUE THREAD

**Issue by pacoxu** [pacoxu/kubeadm-operator#53]
### Goals

- [x] upgrade support for v1.n-1.x to v1.n.y
- - [x] tested v1.23.5 - v1.23.6
- - [x] tested v1.23.5 - v1.24.0
- - [x] tested v1.23.5 - v1.23.5 
- - [ ] tested v1.23.5 - v1.23.5-lts.1
- [x] dry-run upgrade support for v1.n-1.x to v1.n.y
- - [x] tested
- [x] renew certs
- - [x] tested
- [x] upgrade from v1.n-2 to v1.n
- - [x] tested  v1.22.5 - v1.24.0 https://github.com/pacoxu/kubeadm-operator/pull/73
- [x] upgrade: download binary
- - [x] tested
- [x] custom runtime task group
- - [ ] tested

### Non-Goals / Feature Supports

- [ ] non-root : https://github.com/pacoxu/kubeadm-operator/issues/34
- [x] real dry-run upgrade support for v1.n-1.x to v1.n.y
- - [ ] tested

**Comment by pacoxu** [comment]
Renew Demo
```
apiVersion: operator.kubeadm.x-k8s.io/v1alpha1
kind: Operation
metadata:
  name: renew
spec:
  executionMode: Auto
  renewCertificates: {}
```
